language: node_js
cache:
  directories: 
    - ~!@/.npm
node_js:
  - '10.15.3'
git:
  depth: 3
script:
  - yarn build
  - echo 'esta_linea_es_mi_dominio_personalizado' > public/CNAME
deploy:
  name: Elmo@gremlim
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: master
  commit_message: "Elmo@gremlim - Deploy release ${TRAVIS_TAG}"
  fqdn: esta_linea_es_mi_dominio_personalizado
  on:
    branch: develop